### PR TITLE
Read in multiple dicom files 

### PR DESCRIPTION
**Pull request by ckolbPTB**
This allows us to read in multiple dicom files from different folders and combine them to a single IData object. 

Needed for the ISMRM qMRI challenge

### CODE REVIEW

**Review by fzimmermann89 — COMMENTED** [review]
Suggestion/question:

does
 from_dicom_files(path(folder).glob(*.dcm))
A) work type wise?
B)  work in practice? 
C) fail nicely if it is empty? 

.. And a sequence of string can be empty I think..?

**Review by fzimmermann89 — APPROVED** [review]

**Comment by ckolbPTB** [comment]
A) No, Path.glob returns Generator[Path, None, None]
B) Yes
C) now it does

**Comment by fzimmermann89** [comment]
...can we add Generator[Path, None, None] to the types? :D

**Comment by ckolbPTB** [comment]
done

**Comment by fzimmermann89** [comment]
if len(list(filenames)) == 0:
runs the generator till it is exhausted and does not return any more items

so the next time the generator is accessed within the function, it will not return any elements
you could, for example, do
```
filenames = tuple(fileanemes)
if not filenames:
 raise error
```

(btw: len==0 is redundant, as empty list is falsy..)

or undo and not allow the generator usage and force the caller to convert to tuple.
but it would be quite easy to not pay attention to the types and supply the generator and wonder why the function fails...

**Comment by ckolbPTB** [comment]
whenever I try something like `filenames = tuple(fileanemes)` mypy complains because tuple/list... returns list[object] rather than list[str or Path] needed by dicomread.

**Comment by fzimmermann89** [comment]
yes, sorry, you need to give it a new variable name.

https://mypy-play.net/?mypy=latest&python=3.12&gist=7312d8401e7df7fb70a4bd943ccf20bd

so filenames_tuple=tuple(filenames) or sth similar..

**Comment by ckolbPTB** [comment]
yes, I did that but the problem is then later when calling dicomread because `filenames_tuple` will be of typ list[object]

**Comment by fzimmermann89** [comment]
mhm, no idea why this is requiered, but what about
`    filenames_tuple:tuple[Path|str,...]=tuple(filenames)`
without the explicit type hint it doesnt works for if filenames can also be Sequence[str]...

**Comment by ckolbPTB** [comment]
> filenames_tuple:tuple[Path|str,...]=tuple(filenames)

This also did not work leading to mypy errors: Incompatible types in assignment (expression has type "tuple[object, ...]", variable has type "tuple[str] | tuple[Path]")

My current solution is checking after trying to read the files.

**Comment by fzimmermann89** [comment]
argh. when i tried it, i tried it with:
    filenames_tuple:tuple[str|Path]=(*filenames,)
which works.
but posting here, I decided to use tuple instead.. and did not check it again. No clue why this is a difference, must be something with actually iterating the sequences... ? (It also fails without the generator)

But your solution is nicer, feel free to merge.

**Pull request merged**
