### PR TITLE
Update ruff, typos, mypy

### PR DESCRIPTION
**Pull request by fzimmermann89**

### CODE REVIEW

**Review by schuenke — APPROVED** [review]

**Comment by schuenke** [comment]
Should we maybe start using https://pre-commit.ci/ ? It does include weekly autoupdates for all hooks and creates automatic PRs like [this](https://github.com/asottile/pyupgrade/pull/365) if newer versions are available. 

What do you think @ckolbPTB and @fzimmermann89 ?

**Comment by ckolbPTB** [comment]
> Should we maybe start using https://pre-commit.ci/ ? It does include weekly autoupdates for all hooks and creates automatic PRs like [this](https://github.com/asottile/pyupgrade/pull/365) if newer versions are available.
> 
> What do you think @ckolbPTB and @fzimmermann89 ?

If it helps us to stay up to date I think it is worth a try

**Comment by fzimmermann89** [comment]
using pre-commit lite (a github action, running on github) requires valid billing information even if it is free
image

**Comment by fzimmermann89** [comment]
we could use pre-commit.ci, i.e the actions run on their server, not github.
this requires write access to code:
image

**Comment by fzimmermann89** [comment]
I would like uing pre-commit.ci -- not for the updates, which I think will require manual work anyways (either adding new ignores, or fixing things) but for the automatic fix commits in PRs -- when using the github code editor, I often find myself making some whitespace mistakes which are annoying to fix manually. 
On the other hand, this might also result in problems as some of our contributed might not want to handle the merges this could result in....

**Comment by fzimmermann89** [comment]
Ah: "pre-commit.ci autofix
whether to autofix pull requests. when disabled, comment / label "pre-commit.ci autofix" to a pull request to manually trigger auto-fixing.


sounds great! add a label to use autofix!

**Comment by fzimmermann89** [comment]
I added pre-commit.ci.

I disabled mypy in pre-commit.ci as it will not do fixes for mypy anyways and  we would have to run it without checking pytorch type compatibility:
`build of https://github.com/pre-commit/mirrors-mypy:numpy,torch>=2.4.0,types-requests,einops,pydicom,matplotlib,pytest,xsdata,--index-url=https://download.pytorch.org/whl/cpu,--extra-index-url=https://pypi.python.org/simple@v1.11.2 for python@python3 exceeds tier max size 250MiB: 1011.4MiB
`

**Comment by schuenke** [comment]
Yeah, looks nice. But we should merge this as soon as possible, because pre-commit.ci is failing in all other PRs that don't have the config skipping mypy. Lets give it a try! 🚀

**Review by Solo2020vtc — APPROVED** [review]

**Pull request merged**
