### PR TITLE
(Draft) PyTest CI Pipeline and Codecov report

### PR DESCRIPTION
**Pull request by schuenke**

### CODE REVIEW

**Comment by fzimmermann89** [comment]
I know some repos have a nice code coverage and test report in the PRs as well. Is this something we could get to work without much effort?

**Comment by schuenke** [comment]
Yeah, this should work as soon as the codecov Upload token is set as secret for our repo.

**Comment by ckolbPTB** [comment]
> I know some repos have a nice code coverage and test report in the PRs as well. Is this something we could get to work without much effort?

I think this is only available for public repos...

**Comment by fzimmermann89** [comment]
https://github.com/marketplace/actions/pytest-coverage-comment --> Publishes Test Coverage as a PR comment


https://github.com/EnricoMi/publish-unit-test-result-action  --> Publishes Test Results as a comment and gives a nice overview of failures

Similiar: https://github.com/pytest-dev/pytest-github-actions-annotate-failures  --> Add automatic annotations in PRs to test failures


These work for private repos without any additional service or fees...

**Comment by fzimmermann89** [comment]
Something looks wrong.

No test were run (as the missing Phantoms import breaks them). 

But the coverage is greater 0. Are these all code lines which ran on the imports before the first test? 

Also, the file links in the comment do not work...

**Comment by schuenke** [comment]
I will create a new PR directly into main to be independent of the implementations in [ismrmrd_test_data branch](/ckolbPTB/mrpro/tree/ismrmrd_test_data).

**Pull request closed without merging**
