### PR TITLE
Add apply_ to dataclasses

### PR DESCRIPTION
**Pull request by fzimmermann89**
We will need an apply on our dataclasses, both for @ckolbPTB's work as well, and for the rearrangeind und indexing.
As the _to already basically does an recursive apply with memorization, this refactors it such that the _apply can also be used with different functions.

### CODE REVIEW

**Comment by fzimmermann89** [comment]
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #496
* #490
* __->__ #489
* #488

**Comment by fzimmermann89** [comment]
This might be moved outside the movedatamixin at some point, or the mixin will just become a baseclass for our datastuff.
But for now, please already review as-if going int main as is.

**Comment by ckolbPTB** [comment]
I think it would be a good idea to add a test which especially verifies the memo-functionality

**Comment by fzimmermann89** [comment]
moved to #505

**Pull request closed without merging**
