### PR TITLE
Fix ignore flags

### LINKED ISSUE #119: Hardcoded ignore flags
Currently we have the ignore flags which define which raw data we do not use for `KData` hardcoded here:
https://github.com/PTB-MR/mrpro/blob/467a3b387a7893289094b6e8d6dd806b869e86f8/src/mrpro/data/_KData.py#L87

The required ignore flags will depend on the type of scan we want to reconstruct so this should be adaptable by the user. 

Suggestion:
```
    def from_file(
        cls,
        filename: str | Path,
        ktrajectory: KTrajectoryCalculator | KTrajectory | KTrajectoryIsmrmrd,
        header_overwrites: dict[str, object] | None = None,
        dataset_idx: int = -1,
        ignore_flags: AcqFlags = AcqFlags.ACQ_IS_NOISE_MEASUREMENT | AcqFlags.ACQ_IS_SURFACECOILCORRECTIONSCAN_DATA
```

### PR DESCRIPTION
**Pull request by fzimmermann89**
Should now on default ignore all Siemens non-image acquisitions, and flags are configurable.
 
Needs some testing on real data.

Fixes #119

### CODE REVIEW

**Comment by schuenke** [comment]
In general, it lgtm. 

Like you wrote, this needs some testing with real data (ideally with some vendor-specific and some pulseq data).

I was wondering if an option to add additional flags to the default list (when using `ignore_flags = None`) would be a handy feature? Assuming I would like to add a single additional flag, I would image that it would be nice if I wouldn't have to manually list all the defaults plus the additional flag, but just the additional one, no?

**Comment by fzimmermann89** [comment]
To whom it may concern: Please let me know which of the two commits you prefer.
Or if you have suggestions on how to handle ACQ_IS_PARALLEL_CALIBRATION being set on images, but only if also ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING is set (otherwise it is pure calibration data and should by default be ignored)

**Comment by fzimmermann89** [comment]
discussion with @schuenke @koflera  and @ckolbPTB : will go with variant 2 for now.

**Comment by fzimmermann89** [comment]
The code should be correct, when we looked at the diff we only saw the diff between version 1 and version 2: The missing line was the same between both versions.
So for review, just look at the overall changes of this PR.

**Review by ckolbPTB — APPROVED** [review]

**Review by schuenke — APPROVED** [review]
lgtm

**Pull request merged**
