### PR TITLE
Add colab badge to notebooks

### PR DESCRIPTION
**Pull request by ckolbPTB**

### CODE REVIEW

**Comment by fzimmermann89** [comment]
good idea!

maybe have a 
```
try:
  import mrpro
except ImportError
   !pip install mrpro 
    import mrpro

```
or similar block at the beginning of ll example notebooks?

**Comment by fzimmermann89** [comment]
have you considered writing one script that a) adds the cell and b) calls jupytext? I.e. added the conversion also to the script?
then we could call that script from pre-commit, with the mid-term goal enabling to see all changes to docu/examples also locally without relying on github actions..

**Comment by ckolbPTB** [comment]
Tried to add the 
```
try:
  import mrpro
except ImportError
   !pip install mrpro 
    import mrpro
```
block but in the script it is invalid code and when I add it to the notebook during conversion it is detected as a modification to the notebook which leads to an endless loop of translating py to ipynb -> adding cell -> committing -> translating py ti ipynb -> adding cell -> committing...

**Comment by lrlunin** [comment]
> Tried to add the
> 
> ```
> try:
>   import mrpro
> except ImportError
>    !pip install mrpro 
>     import mrpro
> ```
> 
> block but in the script it is invalid code and when I add it to the notebook during conversion it is detected as a modification to the notebook which leads to an endless loop of translating py to ipynb -> adding cell -> committing -> translating py ti ipynb -> adding cell -> committing...

I would add the following code cell in the `.py` files for the installation of mrpro package.
```python
try:
    import mrpro
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", 'mrpro'])
finally:
    import mrpro
```

Unfortunetely it would not be enough only to add this to the notebooks in the docs since the google colab references to the github file representation.

**Comment by lrlunin** [comment]
implemented in #537

**Pull request closed without merging**
