### PR TITLE
 Fix #73: Let test pipeline fail if tests fail

### LINKED ISSUE #73: Failing tests result in green checkmark
Not sure if feature or bug:

Failing pytest tests result in a green checkmark for the action.

At least for me, this was surprising, as it is different for the pre-commit hook checks.

Do we want to change it and have a red check mark if at least one test is failing?
Or do we want to leave the green checkmark to signify that the testing framework worked, even though we had test failures?

(Example https://github.com/ckolbPTB/mrpro/pull/70)

### PR DESCRIPTION
**Pull request by fzimmermann89**
Fixes #73

### CODE REVIEW

**Comment by fzimmermann89** [comment]
I added an additional step that fails if either test errors or test failures occurred.

Why we need this: 
 - We want to have the pipeline fail if a test fails
 - We still want to continue the pipeline if a test fails to create the comment
 - We use a pipeline in the test invocation to get the coverage
 
The other way to do it would be to
- set `pipefail` in the pipeline test, to mark this step as a failure if the pytest command failed in the pipeline
- add an` if: always()` to the commands that would run regardless of the test failure.

The issue with this approach would be, that the comment step etc would run even if the setup failed, not only if the test failed.

So I decided to treat test failures in the pytest step as success, and in the end, fail a dummy step if we have failures to mark the pipeline as a failure.

**Comment by fzimmermann89** [comment]
Please squash before merging.

**Comment by fzimmermann89** [comment]
@schuenke ping :)

**Review by schuenke — APPROVED** [review]
Useful change! Thanks 👍

**Pull request merged**
