### PR TITLE
Add L1Norm Functional

### PR DESCRIPTION
**Pull request by fzimmermann89**
The L1Norm Functional from #295

### CODE REVIEW

**Review by koflera — COMMENTED** [review]
Looks good to me

**Comment by fzimmermann89** [comment]
> Looks good to me

approve?

**Comment by fzimmermann89** [comment]
@ckolbPTB @koflera @schuenke @guastinimara anybody?
this has been somewhat left..

**Comment by fzimmermann89** [comment]
Please remember to do review

**Review by koflera — APPROVED** [review]

**Pull request merged**
