### PR TITLE
update supported python version to 3.10 & 3.11

### LINKED ISSUE #100: pytorch not compatible with python3.12
Add a line suggesting the python version to use in README.
pytorch currently supports Python 3.8-3.11 (https://pytorch.org/get-started/locally/).

### PR DESCRIPTION
**Pull request by schuenke**
Pytorch does not support Python 3.12, yet.

Therefore, I limited the python version in pyproject.toml to ">3.10, <3.12" and adjusted the badge in the README

closes #100

### CODE REVIEW

**Comment by fzimmermann89** [comment]
I would NOT limit our compatibility because a dependency does not support it. Only if our code is not ready for a new version.

I'd limit the python compatibility to `>=3.10,<3.2`

I agree with the batch / not mentioning python 3.12 in the readme, not to confuse users,
 but veto the requirements change.

Furthermore, pytorch nightly supports python 3.12.

**Review by fzimmermann89 — CHANGES_REQUESTED** [review]
I'd prefer not to limit our compatibility based on compartibility of dependencies. This is something the package manager should take care of.

**Comment by schuenke** [comment]
> I would NOT limit our compatibility because a dependency does not support it. Only if our code is not ready for a new version.
> 
> I'd limit the python compatibility to `>=3.10,<3.2`
> 
> I agree with the batch / not mentioning python 3.12 in the readme, not to confuse users, but veto the requirements change.
> 
> Furthermore, pytorch nightly supports python 3.12.

I would argue that we currently cannot test our code in 3.12, which means that in general we cannot guarantee that our code is 3.12 compatible, which IMO means that we do not support it, no ?!

**Comment by fzimmermann89** [comment]
Yes, but semantic versioning should mean all code running under 3.11 should run under 3.12, right?

Edit: But python is not using semver... 

Ok,....

**Review by fzimmermann89 — APPROVED** [review]

**Pull request merged**
